version: "3.7"

services:
  app:
    image: paper_recommender_web:latest
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    volumes:
      - ./.docker/data/db1:/var/lib/mysql
      - ./init_db.sql:/docker-entrypoint-initdb.d/db.sql:ro
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: pseudo_database